platform :ios, '9.0'
use_frameworks!

target 'Calendouer' do
    pod 'SDWebImage', '~> 3.8'
    pod 'SnapKit', '~> 3.0.2'
    pod 'lottie-ios'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end

